name: boats-app
services:
  api:
    build:
      context: ./boats-api
      dockerfile: Dockerfile
    image: boats-api:dev
    working_dir: /app
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8080:8080"
    volumes:
      - ./boats-api:/app
      - gradle-cache:/home/gradle/.gradle
      - api-build:/app/build

  ui:
    build:
      context: ./boats-ui
      dockerfile: Dockerfile
    image: boats-ui:dev
    working_dir: /app
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "4200:4200"
    volumes:
      - ./boats-ui:/app
      - ui-node-modules:/app/node_modules
    depends_on:
     - api

volumes:
  gradle-cache:
  api-build:
  ui-node-modules:
